steps:
  - name: 'python:3.12'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt  # Install dependencies
        python main.py  # Run your script

logsBucket: gs://gsheet-to-gbq-logs-12345  # Replace with your actual GCS bucket for logs

artifacts:
  objects:
    location: gs://gsheet-to-gbq-logs-12345/output/  # Adjust path as needed
    paths: 
      - output_file.csv  # Replace with actual output files

timeout: 900s  # Set timeout (15 minutes)
