steps:
  - name: 'python:3.12'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        pip install -r requirements.txt  # Corrected filename
        python main.py

logsBucket: gs://gsheet-to-gbq-logs-12345

options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: task-725@gsheet-to-gbq.iam.gserviceaccount.com
