steps:
  - name: 'python:3.12'
    entrypoint: 'python'
    args: ['main.py']

logsBucket: gs://gsheet-to-gbq-logs-12345

options:
  logging: GCS_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

serviceAccount: task-725@gsheet-to-gbq.iam.gserviceaccount.com
